#!/usr/bin/env python3
"""nollmkb interactive setup — generate .env with one command.

Usage:
    uv run python3 scripts/setup.py
"""

import os
import sys
import shutil
import subprocess
import hashlib
from pathlib import Path


def _detect_cuda() -> bool:
    """Check if CUDA is available on this machine."""
    return shutil.which("nvidia-smi") is not None


def _detect_tailscale() -> tuple[bool, str]:
    """Check if Tailscale is running and get its IP."""
    ip = ""
    try:
        result = subprocess.run(
            ["tailscale", "ip", "-4"],
            capture_output=True, text=True, timeout=5,
        )
        ip = result.stdout.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return bool(ip), ip


def _prompt(prompt: str, default: str = "") -> str:
    """Ask user a question, return input or default on empty."""
    suffix = f" [{default}]: " if default else ": "
    raw = input(prompt + suffix).strip()
    return raw if raw else default


def _prompt_yesno(prompt: str, default: bool = True) -> bool:
    """Ask yes/no question. Enter = default."""
    yn = "Y/n" if default else "y/N"
    raw = input(f"{prompt} [{yn}]: ").strip().lower()
    if not raw:
        return default
    return raw.startswith("y")


def _generate_hash(password: str) -> str:
    return hashlib.sha256(password.encode()).hexdigest()


def main():
    # detect system state
    env_file = Path(__file__).resolve().parent.parent / ".env"
    has_cuda = _detect_cuda()
    has_tailscale, ts_ip = _detect_tailscale()

    cfg: dict[str, str] = {}

    print()
    print("=" * 60)
    print("  nollmkb setup — generate .env configuration")
    print("=" * 60)
    print()
    print("Press Enter at any prompt to accept the default shown in brackets.")
    print()

    # Step 1: host
    print("[1/4]  Bind address")
    print(f"  Default: 127.0.0.1 (only this machine can access)")
    if has_tailscale:
        print(f"  Detected Tailscale IP: {ts_ip}")
        use_remote = _prompt_yesno("  Allow remote access via Tailscale?", True)
        if use_remote:
            cfg["NOLLMKB_HOST"] = _prompt("    Tailscale IP", ts_ip)
    else:
        use_remote = _prompt_yesno("  Allow remote access? (requires Tailscale)", False)
        if use_remote:
            cfg["NOLLMKB_HOST"] = _prompt("    IP or 0.0.0.0", "0.0.0.0")
    print()

    # Step 2: auth
    print("[2/4]  API authorization (optional)")
    if _prompt_yesno("  Add password protection? (recommended for remote access)", use_remote):
        import getpass
        pw = getpass.getpass("    Password (Enter to skip): ")
        if pw:
            cfg["NOLLMKB_API_KEY_HASH"] = _generate_hash(pw)
            print(f"    Hash: {cfg['NOLLMKB_API_KEY_HASH'][:16]}... (stored in .env, not the password)")
        else:
            print("    Skipped — no password will be required.")
    print()

    # Step 3: device
    print("[3/4]  Compute device")
    if has_cuda:
        cfg["NOLLMKB_DEVICE"] = "cuda"
        print(f"  Detected CUDA (GPU). Default: cuda")
    else:
        cfg["NOLLMKB_DEVICE"] = "cpu"
        print(f"  No GPU detected. Default: cpu (slower)")
    choice = _prompt("  Device (cuda/cpu)", cfg.get("NOLLMKB_DEVICE", "cuda"))
    if choice:
        cfg["NOLLMKB_DEVICE"] = choice
    print()

    # Step 4: paths
    print("[4/4]  Custom paths (optional, skip to use defaults)")
    custom = _prompt_yesno("  Customize storage directories?", False)
    if custom:
        if v := _prompt("    Document directory", "../inputs"):
            cfg["NOLLMKB_DOCS_DIR"] = v
        if v := _prompt("    ChromaDB storage", "../chromadb_storage"):
            cfg["NOLLMKB_KB_DIR"] = v
        if v := _prompt("    Wiki notes", "../wiki"):
            cfg["NOLLMKB_WIKI_DIR"] = v
        if v := _prompt("    Log directory", "../logs"):
            cfg["NOLLMKB_LOG_DIR"] = v
    print()

    # generate .env content
    lines = ["# nollmkb configuration — generated by scripts/setup.py", ""]
    for key in ["NOLLMKB_HOST", "NOLLMKB_DEVICE", "NOLLMKB_API_KEY_HASH",
                "NOLLMKB_DOCS_DIR", "NOLLMKB_KB_DIR", "NOLLMKB_WIKI_DIR", "NOLLMKB_LOG_DIR"]:
        if key in cfg:
            lines.append(f"{key}={cfg[key]}")
        else:
            lines.append(f"#{key}=")
    # always include commented reference lines
    for line in [
        "",
        "# Full reference — uncomment and edit as needed:",
        "#NOLLMKB_COLLECTION=nollmkb",
        "#NOLLMKB_HASH_FILE=<KB_DIR>/file_hashes.json",
        "#NOLLMKB_LOG_LEVEL=INFO",
    ]:
        lines.append(line)
    content = "\n".join(lines) + "\n"

    # preview
    print("=" * 60)
    print("  Preview — this is what would be written to .env:")
    print("=" * 60)
    for line in content.strip().split("\n"):
        print(f"  | {line}")
    print()

    if env_file.exists():
        print(f"  ⚠  {env_file} already exists and would be overwritten.")
    else:
        print(f"  ✓ {env_file} does not exist yet — safe to write.")

    print()
    if _prompt_yesno("Write this .env file?", False):
        env_file.write_text(content, encoding="utf-8")
        print(f"  ✓ Written to {env_file}")
        print()
        print("  Next step: uv run python3 server.py")
    else:
        print()
        print("  Skipped. Copy the preview above manually into your .env file.")
        print(f"  Or re-run this script later to generate {env_file}")


if __name__ == "__main__":
    main()
